### ISSUE TITLE
msan is angry about uninitialized memory in zstd 0.8.0

### ISSUE THREAD

**Issue by velavokr** [Cyan4973/zstd#281] opened 2016-08-10 19:11 UTC
Hi!

Our clang memory sanitizer is angry about uninitialized memory from [here](https://github.com/Cyan4973/zstd/blob/master/lib/compress/zstd_compress.c#L276).

The msan trace is [here](http://pastebin.com/zsinyxFW). 
The zstd is 0.8.0.
The clang is 3.7.1.

Adding ```memset(zc->workSpace, 0, neededSpace);``` after line 277 helps. Adding ```reset = 1;``` doesn't.

**Comment by Cyan4973** [comment] 2016-08-10 22:18
Thanks for reporting @velavokr .

It seems the issue is currently non consequential, because affected values are not used later on.
That being said, it's nonetheless better to fix it, so I'll take care of it.

**Comment by Cyan4973** [comment] 2016-08-11 18:45
I now remember,
I tried to use memory sanitizer as part of the CI test suite,
but for some reason, `datagen.c` fails it, in what seems to be a false positive.

Anyway, due to this enduring problem, for which I've no good solution,
I've been unable to use `msan` in the CI test suite.
a pity...

The option is still there though : `make msan`

**Comment by Cyan4973** [comment] 2016-08-11 20:15
While the `datagen` false positive problem is still there, visible in `zbufftest`,
the specific issue of this thread seems solved by latest update in "dev" branch.

**Comment by velavokr** [comment] 2016-08-11 21:34
Yes, it works, thanks!

**Comment by Cyan4973** [comment] 2016-08-18 15:14
fixed in v0.8.1

**Closed by Cyan4973** 2016-08-18 15:14 UTC
