### ISSUE TITLE
`zstd --rm --test` removes file(s) under test.

### ISSUE THREAD

**Issue by amnilsson** [Cyan4973/zstd#260] opened 2016-07-25 19:22 UTC
I defined the following alias in Bash, being accustomed to and preferring the default behaviour of bzip2, gzip, and xz: `alias zstd='zstd --rm'`

Then, when calling `zstd --test <file>`, and thus in effect `zstd --rm --test <file>`, zstd (v0.7.4) removed the input file. I find this counterintuitive.

Technically the description of `--rm` is correct. The file was successfully decompressed, albeit just into memory. But as a user I find that testing the integrity of a compressed file as in `--test`, is different from decompressing it as in `-d`.

OT: Thank you for all your hard work. The compression ratio of `-22 --ultra` compared to LZMA2 is impressive, especially when taking the difference in decompression speed into account.

**Comment by Cyan4973** [comment] 2016-07-25 19:47
Thanks for report @amnilsson .

You are totally right, testing the file should not delete it.
You guessed correctly why it happens this way.
This will be changed.

**Comment by Cyan4973** [comment] 2016-07-25 22:28
> Then, when calling zstd --test <file>, and thus in effect zstd --rm --test <file>, zstd (v0.7.4) removed the input file. I find this counterintuitive

I've been trying to reproduce the bug, using latest dev branch and release v0.7.4,
and so far, I'm unable to reproduce it. `<file>` remains present after a `--rm --test` command.
Not sure why results are different ...

**Comment by Cyan4973** [comment] 2016-07-25 22:52
Thanks, the issue is supposed to be fixed in latest development branch.
It will be part of the next release.
Regards

**Comment by amnilsson** [comment] 2016-07-26 11:08
Happy to help! :-)

Tried the dev08 branch. It seems to be working. Awesome! Thank you!

**Closed** 2016-07-26 11:08 UTC
