### ISSUE TITLE
lost 20% of decompression speed in v0.4

### ISSUE THREAD

**Issue by inikep** [Cyan4973/zstd#82] opened 2015-11-30 11:44 UTC
It seems that you have lost 20% of decompression speed in v0.4:

| Compressor name             | Compression| Decompress.| Compr. size | Ratio |
| ---------------             | -----------| -----------| ----------- | ----- |
| zstd_HC v0.3.6 level 1      |   250 MB/s |   529 MB/s |    51230550 | 48.86 |
| zstd_HC v0.3.6 level 2      |   186 MB/s |   498 MB/s |    49678572 | 47.38 |
| zstd_HC v0.3.6 level 3      |    90 MB/s |   484 MB/s |    48838293 | 46.58 |
| zstd_HC v0.3.6 level 4      |    75 MB/s |   474 MB/s |    48423913 | 46.18 |
| zstd_HC v0.3.6 level 5      |    61 MB/s |   467 MB/s |    46480999 | 44.33 |
| zstd_HC v0.3.6 level 6      |    40 MB/s |   477 MB/s |    45723093 | 43.60 |
| zstd_HC v0.3.6 level 7      |    28 MB/s |   480 MB/s |    44803941 | 42.73 |
| zstd_HC v0.3.6 level 8      |    21 MB/s |   475 MB/s |    44511976 | 42.45 |
| zstd_HC v0.3.6 level 9      |    15 MB/s |   497 MB/s |    43899996 | 41.87 |
| zstd_HC v0.3.6 level 10     |    16 MB/s |   493 MB/s |    43845344 | 41.81 |
| zstd_HC v0.3.6 level 11     |    15 MB/s |   491 MB/s |    42506862 | 40.54 |
| zstd_HC v0.3.6 level 12     |    11 MB/s |   493 MB/s |    42402232 | 40.44 |
| zstd v0.4 level 1           |   244 MB/s |   492 MB/s |    51160301 | 48.79 |
| zstd v0.4 level 2           |   176 MB/s |   443 MB/s |    49719335 | 47.42 |
| zstd v0.4 level 3           |    88 MB/s |   422 MB/s |    48749022 | 46.49 |
| zstd v0.4 level 4           |    74 MB/s |   402 MB/s |    48352259 | 46.11 |
| zstd v0.4 level 5           |    69 MB/s |   387 MB/s |    46389082 | 44.24 |
| zstd v0.4 level 6           |    36 MB/s |   387 MB/s |    45525313 | 43.42 |
| zstd v0.4 level 7           |    29 MB/s |   390 MB/s |    44805120 | 42.73 |
| zstd v0.4 level 8           |    23 MB/s |   389 MB/s |    44509894 | 42.45 |
| zstd v0.4 level 9           |    16 MB/s |   402 MB/s |    43892280 | 41.86 |
| zstd v0.4 level 10          |    18 MB/s |   407 MB/s |    43807530 | 41.78 |
| zstd v0.4 level 11          |    15 MB/s |   417 MB/s |    42498160 | 40.53 |
| zstd v0.4 level 12          |    11 MB/s |   406 MB/s |    42394424 | 40.43 |

**Comment by Cyan4973** [comment] 2015-11-30 11:58
There are 2 potential culprits : 
- One or some of the last fixes made. 
   + Notably, I had to fix some 32-bits specific issues during the last days, and did not re-test speed.
   + I could try to track them one by one to see if one or some of them introduce a regression.

- Instruction loop Alignment.
There is a big issue with GCC : it doesn't pay attention to instruction alignment well enough, notably for hot loops. It happens to make a huge speed difference for Huff0 and FSE on latest Intel Core CPU. As a consequence, decompression speed can vary a lot, just by virtue of "where the code is", that is almost randomly after each code change, including code changed outside of `zstd_decompress.c`. 

I opened an issue about it on GCC, and although they acknowledge the issue, they seem to not care to do anything about it.

This is a problem, as tracking speed changes on the decompression algorithm is a total nightmare : no way to know if the speed difference observed is related to the latest code change or to some random alignment property.

As a consequence, I'm considering to move from GCC to another compiler free of such instability. I still have to test and select one though.

**Comment by inikep** [comment] 2015-11-30 12:52
The above results are obtained using 1 core of Intel Core i5-4300U, Windows 10 64-bit (MinGW-w64 compilation under gcc 4.8.3 with -O3 -fomit-frame-pointer -fstrict-aliasing -fforce-addr -ffast-math flags).

Moving to another compiler doesn't solve a problem because other people will use GCC (and zstd is open-source). The decompression function is no so big so I think you can try to find what was changed between v0.4 and v0.3.6 which worked fine.

**Comment by Cyan4973** [comment] 2015-11-30 13:26
I will. Understand this is a never-ending effort though : any change anywhere in the code, even totally unrelated, can trigger such 20% decompression speed difference. Some of these changes are valid fixes, so they *must* be done, I can't simply undo them. But compensating their indirect consequence on decompression speed requires creative work-around, basically strange constructions just to "push" instructions in a way which is randomly good for hot loop alignment. A real nightmare. I need something more stable.

**Comment by tomByrer** [comment] 2015-11-30 17:13
Does seem @inikep's results show better compression size; could be an influence on speed?

>  GCC : it doesn't pay attention to instruction alignment well enough, notably for hot loops.... I opened an issue about it on GCC, and although they acknowledge the issue, they seem to not care to do anything about it.

I can understand GCC's position somewhat.  I used hand-edit ASM for DSP years ago.  I reordered instructions & remove redundant opcodes.   But I found the (then new) Core2Duo made much of my work unneeded since the CPU did much of my work for me.
I've heard that the Intel compilers make the fastest executables.
https://software.intel.com/en-us/c-compilers

**Comment by Cyan4973** [comment] 2015-11-30 19:11
> Does seem @inikep's results show better compression size; could be an influence on speed?

It could explain for 1-3% difference, but not 20 %.

I've been losing quite some more time on this today. And the worst scenario is predictably happening.
I can make a few changes of code, resulting in better decompression speed ... for a given set of compiler version, parameters and target. But then switch to another system, and in turns out to be worse.

This is a total nightmare. In fact, I suspect that the changes themselves don't bring much to speed, but its impossible to measure, since the impact to instruction alignment dwarf any other potential effect.

That means there is no stable solution. +/- speed is reached out of random luck.

I can't imagine a worse situation to be in. A solution is required to stabilize that.

As an example, when compiling just `huff0`, a solution was to use `-falign-loops=32`. It's better for hot loops, but worse for everything else.
Unfortunately, what worked for a simple library doesn't work for `zstd`, since it's too large, so the global effect is negative. 

I can imagine 2 other possibilities, none of which I have yet expertise in : 
- Add a few assembler directives (only for x64 target) to manually achieve hot instruction loop alignment (and only those loops).
- Use PGO assisted build, in the hope that it will understand which part of the code is hot or not, and apply clever instruction alignment. hopefully.

> I can understand GCC's position somewhat. 

Well, on my side, I don't understand how a known performance stability problem with a swing of up to 20% can be considered uninteresting. My understanding is that compiler developers chase micro-gains, even when it introduces serious complexity, such as automatic vectorization. 20% cannot be qualified as micro-gain, and alignment is not expected to be "serious complexity" (for a compiler like gcc). But this is nonetheless not worth investigating ? There is something I don't understand here.

**Comment by Cyan4973** [comment] 2015-11-30 22:25
Latest update in "dev" branch is trying to improve the situation.
It is still a bit random, but seems overall a bit more positive than negative.
If your program experience a -20% performance effect with 0.4, this update is likely to produce an improvement.

On a related note, I can now confirm that PGO assisted build are more stable performance wise. It always end up at the top of the possible performance range.

It's only a partial solution though : I may be able to create a `makefile` which builds a command line utility using PGO, and hope to transfer this capability to dll build (which I haven't done yet).
But this will not help for people integrating directly from source.

Anyway, if at least it makes performance stable, it's still good news : I should be able to make some new modifications now with less fear that it will lead to random results. Thus, it will be possible to tell if the modification was neutral, beneficial or detrimental, a much wanted ability.

**Comment by tomByrer** [comment] 2015-12-01 01:00
> , I don't understand how a known performance stability problem with a swing of up to 20% can be considered uninteresting.

Yes, unstable compiling would prevent the 'scientific method' to speed testing.

**Comment by Cyan4973** [comment] 2015-12-01 12:08
Proposed change merged into master

**Comment by Cyan4973** [comment] 2015-12-02 11:51
Issue seems solved in 0.4.1.
Some other leads proposed by @nemequ.
Discussion at : http://encode.ru/threads/2119-Zstandard?p=45797&viewfull=1#post45797

**Closed by Cyan4973** 2015-12-02 11:51 UTC
